# Generated by Django 4.2.14 on 2026-02-24 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_first_name_profile_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
